### ISSUE TITLE
[UI] add a link to the application tile

### ISSUE THREAD

**Issue by mingmxu** [argoproj-labs/argocd-operator#1173]
**Is your feature request related to a problem? Please describe.**
When exploring the application in `/applications`, I'm not able to write-click and open it in a new tab, tried both Chrome and Safari. It makes things hard to navigate multiple applications.

**Describe the solution you'd like**
Add an link/action to support `open link in new tab/window`

**Describe alternatives you've considered**

**Additional context**

**Comment by svghadi** [comment]
Hi @mingmxu, thank you for the enhancement suggestion. I agree that ArgoCD should allow users to open applications in a new tab. However, the operator doesn't have its own separate UI component. The UI used to interact with ArgoCD Applications is part of ArgoCD itself, so this enhancement belongs to [argoproj/argo-cd](https://github.com/argoproj/argo-cd) project. 

Please feel free to create an issue in [argoproj/argo-cd](https://github.com/argoproj/argo-cd) project to discuss this further. I am closing this issue here as it doesn't belong to this repository.
