### ISSUE TITLE
Unable to get a working install, bare metal kubeadm 1.18

### ISSUE THREAD

**Issue by briantopping** [argoproj-labs/argocd-operator#133]
Greetings, thanks for such a promising tool set!

I'm trying to install the operator using the OLM on bare metal k8s 1.18 via Kubeadm. Not having much luck. The manifests off operatorhub.io use a namespace of `my-argocd-operator` and that's the only place I can put an `ArgoCD` CR that it will get picked up. 

Once it does, the sample app in the primary docs does not work to the default namespace:

```
services is forbidden: User "system:serviceaccount:argocd:argocd-application-controller" cannot create resource "services" in API group "" in the namespace "default"
```

Not sure where to go from here..

**Comment by tylerauerbeck** [comment]
@briantopping I believe this is expected. Using OLM, you should be able to deploy the argocd-operator to any namespace that you want. However, with the current implementation of this operator, it will only pick up ArgoCD CR's in the namespace that the operator is deployed in. There is an open issue for this one here: #107 

As for the second part of your issue, it looks like this is just because that serviceaccount doesn't have access to deploy to the `default` namespace. That error looks a bit odd though because from what you're saying you deployed to the `my-argocd-operator` namespace, but that error refers to a serviceaccount in the `argocd` namespace. This may just be an artifact of working from an example though. I would recommend just making sure that all of the examples your working from are deploying/referencing things in the right namespace -- but happy to help out more if you can provide further details.

**Comment by briantopping** [comment]
Hi @tylerauerbeck thanks a bunch for the quick response. I will have to apologize in advance if this turns into a support ticket.

The example I did is against `argocd` namespace because I saw some slack threads that indicated the stack did not work well from other namespaces, so I was just being sure that I wasn't missing anything (it being a weekend and all).

Sounds like the right thing to do is leave the namespace as `my-argocd-operator` and deploy the `ArgoCD` object there. That's totally fine on my end. 

This is where I'm potentially going to be embarrassed: I scoured the the docs and couldn't find any practice for setting up permissions. Is that correct? I'm not against setting perms, just not wanting to get off the rails with my config and break the level  5 operator "OLM autopilot". Thanks!
